In [2]:
from sklearn.preprocessing import OneHotEncoder
import numpy

In [3]:
documents=["people watch movie",
           "people watch cricket",
           "people like movie",
           "people like cricket",
           "people watch movie"]

In [4]:
tokens=[sentence.lower().split() for sentence in documents]
print(tokens)

[['people', 'watch', 'movie'], ['people', 'watch', 'cricket'], ['people', 'like', 'movie'], ['people', 'like', 'cricket'], ['people', 'watch', 'movie']]


In [5]:
all_words= [[word] for sentence in tokens for word in sentence]
print(all_words)

[['people'], ['watch'], ['movie'], ['people'], ['watch'], ['cricket'], ['people'], ['like'], ['movie'], ['people'], ['like'], ['cricket'], ['people'], ['watch'], ['movie']]


In [6]:
oneHot_encoder=OneHotEncoder(sparse_output=False)
oneHot_encoded=oneHot_encoder.fit(all_words)
print(oneHot_encoded.categories_)


[array(['cricket', 'like', 'movie', 'people', 'watch'], dtype=object)]


In [7]:
print(oneHot_encoded.categories_[0])

['cricket' 'like' 'movie' 'people' 'watch']


In [8]:
for sentence in tokens:
    oneHot_encoded_sentence=oneHot_encoder.transform([[word] for word in sentence])
    print(sentence)
    print(oneHot_encoded_sentence)

['people', 'watch', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
['people', 'watch', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
['people', 'like', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
['people', 'like', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
['people', 'watch', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]


In [ ]:
BAG OF WORDS Practice

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [ ]:
documents=["people watch movie and people watch cricket",
           "people watch cricket and people like movie",
              "people like movie and people like cricket",
              "people like cricket and people watch movie",
                "people watch movie"]