In [102]:
from sklearn.preprocessing import OneHotEncoder
import numpy

In [103]:
documents=["people watch movie",
           "people watch cricket",
           "people like movie",
           "people like cricket",
           "people watch movie"]

In [104]:
tokens=[sentence.lower().split() for sentence in documents]
print(tokens)

[['people', 'watch', 'movie'], ['people', 'watch', 'cricket'], ['people', 'like', 'movie'], ['people', 'like', 'cricket'], ['people', 'watch', 'movie']]


In [105]:
all_words= [[word] for sentence in tokens for word in sentence]
print(all_words)

[['people'], ['watch'], ['movie'], ['people'], ['watch'], ['cricket'], ['people'], ['like'], ['movie'], ['people'], ['like'], ['cricket'], ['people'], ['watch'], ['movie']]


In [106]:
oneHot_encoder=OneHotEncoder(sparse_output=False)
oneHot_encoded=oneHot_encoder.fit(all_words)
print(oneHot_encoded.categories_)


[array(['cricket', 'like', 'movie', 'people', 'watch'], dtype=object)]


In [107]:
print(oneHot_encoded.categories_[0])

['cricket' 'like' 'movie' 'people' 'watch']


In [108]:
for sentence in tokens:
    oneHot_encoded_sentence=oneHot_encoder.transform([[word] for word in sentence])
    print(sentence)
    print(oneHot_encoded_sentence)

['people', 'watch', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
['people', 'watch', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
['people', 'like', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
['people', 'like', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
['people', 'watch', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]


In [109]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [110]:
documents=["people watch movie and people watch cricket",
           "people watch cricket and people like movie",
              "people like movie and people like cricket",
              "people like cricket and people watch movie",
                "people watch movie"]

In [111]:
vector_matrix=vectorizer.fit_transform(documents)

In [112]:
vector_matrix

<5x6 sparse matrix of type '<class 'numpy.int64'>'
	with 25 stored elements in Compressed Sparse Row format>

In [113]:
print("Vector Matrix:\n",vector_matrix.toarray())

Vector Matrix:
 [[1 1 0 1 2 2]
 [1 1 1 1 2 1]
 [1 1 2 1 2 0]
 [1 1 1 1 2 1]
 [0 0 0 1 1 1]]


In [114]:
from sklearn.feature_extraction.text import CountVectorizer

In [115]:
bow=CountVectorizer()

In [116]:
bow_matrix=bow.fit_transform(documents)

In [117]:
print("Bow matrix:\n",bow_matrix.toarray())

Bow matrix:
 [[1 1 0 1 2 2]
 [1 1 1 1 2 1]
 [1 1 2 1 2 0]
 [1 1 1 1 2 1]
 [0 0 0 1 1 1]]


In [ ]:
bow.get_feature_names_out()

In [ ]:
print(bow.get_feature_names_out)