In [16]:
from sklearn.preprocessing import OneHotEncoder
import numpy

In [17]:
documents=["people watch movie",
           "people watch cricket",
           "people like movie",
           "people like cricket",
           "people watch movie"]

In [18]:
tokens=[sentence.lower().split() for sentence in documents]
print(tokens)

[['people', 'watch', 'movie'], ['people', 'watch', 'cricket'], ['people', 'like', 'movie'], ['people', 'like', 'cricket'], ['people', 'watch', 'movie']]


In [19]:
all_words= [[word] for sentence in tokens for word in sentence]
print(all_words)

[['people'], ['watch'], ['movie'], ['people'], ['watch'], ['cricket'], ['people'], ['like'], ['movie'], ['people'], ['like'], ['cricket'], ['people'], ['watch'], ['movie']]


In [20]:
oneHot_encoder=OneHotEncoder(sparse_output=False)
oneHot_encoded=oneHot_encoder.fit(all_words)
print(oneHot_encoded.categories_)


[array(['cricket', 'like', 'movie', 'people', 'watch'], dtype=object)]


In [21]:
print(oneHot_encoded.categories_[0])

['cricket' 'like' 'movie' 'people' 'watch']


In [ ]:
for sentence in tokens:
    oneHot_encoded_sentence=oneHot_encoder.transform([[word] for word in sentence])
    print(sentence)
    print(oneHot_encoded_sentence)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
