OneHotEncoder

In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy

In [2]:
documents=["people watch movie",
           "people watch cricket",
           "people like movie",
           "people like cricket",
           "people watch movie"]

In [3]:
tokens=[sentence.lower().split() for sentence in documents]
print(tokens)

[['people', 'watch', 'movie'], ['people', 'watch', 'cricket'], ['people', 'like', 'movie'], ['people', 'like', 'cricket'], ['people', 'watch', 'movie']]


In [4]:
all_words= [[word] for sentence in tokens for word in sentence]
print(all_words)

[['people'], ['watch'], ['movie'], ['people'], ['watch'], ['cricket'], ['people'], ['like'], ['movie'], ['people'], ['like'], ['cricket'], ['people'], ['watch'], ['movie']]


In [5]:
oneHot_encoder=OneHotEncoder(sparse_output=False)
oneHot_encoded=oneHot_encoder.fit(all_words)
print(oneHot_encoded.categories_)


[array(['cricket', 'like', 'movie', 'people', 'watch'], dtype=object)]


In [6]:
print(oneHot_encoded.categories_[0])

['cricket' 'like' 'movie' 'people' 'watch']


In [7]:
for sentence in tokens:
    oneHot_encoded_sentence=oneHot_encoder.transform([[word] for word in sentence])
    print(sentence)
    print(oneHot_encoded_sentence)

['people', 'watch', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
['people', 'watch', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
['people', 'like', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
['people', 'like', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
['people', 'watch', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]


BagOfWords(BoW)

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [9]:
documents=["people watch movie and people watch cricket",
           "people watch cricket and people like movie",
              "people like movie and people like cricket",
              "people like cricket and people watch movie",
                "people watch movie"]

In [10]:
documents=["A method on transformers which fits the estimator and returns the transformed training data. It takes parameters as in fit and its output should have the same shape as calling .fit(X, ...).transform(X). There are nonetheless rare cases where .fit_transform(X, ...) and .fit(X, ...).transform(X) do not return the same value, wherein training data needs to be handled differently (due to model blending in stacked ensembles, for instance; such cases should be clearly documented). Transductive transformers may also provide fit_transform but not transform."]

In [11]:
vector_matrix=vectorizer.fit_transform(documents)

In [12]:
vector_matrix

<1x58 sparse matrix of type '<class 'numpy.int64'>'
	with 58 stored elements in Compressed Sparse Row format>

In [13]:
print("Vector Matrix:\n",vector_matrix.toarray())

Vector Matrix:
 [[1 3 1 2 2 1 1 1 2 1 2 1 1 1 1 1 1 3 2 1 1 1 1 2 1 1 1 1 1 1 1 1 2 1 1 1
  1 1 1 1 2 1 2 1 1 1 4 1 2 2 1 3 1 2 1 1 1 1]]


In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
bow=CountVectorizer()

In [16]:
bow_matrix=bow.fit_transform(documents)

In [17]:
print("Bow matrix:\n",bow_matrix.toarray())

Bow matrix:
 [[1 3 1 2 2 1 1 1 2 1 2 1 1 1 1 1 1 3 2 1 1 1 1 2 1 1 1 1 1 1 1 1 2 1 1 1
  1 1 1 1 2 1 2 1 1 1 4 1 2 2 1 3 1 2 1 1 1 1]]


In [18]:
bow.get_feature_names_out()

array(['also', 'and', 'are', 'as', 'be', 'blending', 'but', 'calling',
       'cases', 'clearly', 'data', 'differently', 'do', 'documented',
       'due', 'ensembles', 'estimator', 'fit', 'fit_transform', 'fits',
       'for', 'handled', 'have', 'in', 'instance', 'it', 'its', 'may',
       'method', 'model', 'needs', 'nonetheless', 'not', 'on', 'output',
       'parameters', 'provide', 'rare', 'return', 'returns', 'same',
       'shape', 'should', 'stacked', 'such', 'takes', 'the', 'there',
       'to', 'training', 'transductive', 'transform', 'transformed',
       'transformers', 'value', 'where', 'wherein', 'which'], dtype=object)

In [19]:
print(bow.get_feature_names_out)

<bound method CountVectorizer.get_feature_names_out of CountVectorizer()>


TF-IDF

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
documents=["people watch movie and people watch cricket",
           "people watch cricket and people like movie",
              "people like movie and people like cricket",
              "people like cricket and people watch movie",
                "people watch movie"]

In [4]:
tf_idf=TfidfVectorizer()

In [8]:
tf_idf_vector=tf_idf.fit_transform(documents)

In [9]:
tf_idf_vector

<5x6 sparse matrix of type '<class 'numpy.float64'>'
	with 25 stored elements in Compressed Sparse Row format>

In [11]:
tf_idf_vector.toarray()

array([[0.32313873, 0.32313873, 0.        , 0.27330867, 0.54661734,
        0.64627747],
       [0.35377632, 0.35377632, 0.42054572, 0.29922174, 0.59844348,
        0.35377632],
       [0.29841863, 0.29841863, 0.70948038, 0.25240057, 0.50480113,
        0.        ],
       [0.35377632, 0.35377632, 0.42054572, 0.29922174, 0.59844348,
        0.35377632],
       [0.        , 0.        , 0.        , 0.54249496, 0.54249496,
        0.64140349]])

In [12]:
for vector in tf_idf_vector.toarray():
    print(vector)

[0.32313873 0.32313873 0.         0.27330867 0.54661734 0.64627747]
[0.35377632 0.35377632 0.42054572 0.29922174 0.59844348 0.35377632]
[0.29841863 0.29841863 0.70948038 0.25240057 0.50480113 0.        ]
[0.35377632 0.35377632 0.42054572 0.29922174 0.59844348 0.35377632]
[0.         0.         0.         0.54249496 0.54249496 0.64140349]


In [13]:
tf_idf.get_feature_names_out()

array(['and', 'cricket', 'like', 'movie', 'people', 'watch'], dtype=object)

In [14]:
print("vocabulary:", tf_idf.get_feature_names_out())

vocabulary: ['and' 'cricket' 'like' 'movie' 'people' 'watch']
